# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            MaoZheYang
tagline:          好奇这个世界
url:              http://www.maozheyang.com
paginate:         1
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/maozheyang/mao

pages_list: 
  My Family: 'http://blog.utopia-project.com'
  Archive: '/archive'
  About: '/about'
  RSS: '/atom.xml'

